V2
ltvco/ecr-cleaner pull request #1
Opened 2024-01-11 20:20 UTC by will-beep-lamm

ecr-cleanup ground up rework

2024-05-17 14:43 UTC, jdziat requested changes
Just need one small tweak and we're all set

2024-05-17 14:43 UTC, jdziat commented on clean/clean.go
> +	arnmap := map[string]string{
Believe this should be configurable

2024-05-17 18:24 UTC, will-beep-lamm commented on clean/clean.go
> +	arnmap := map[string]string{
So you would like the user to input their own arn for the role to use?

2024-05-17 19:04 UTC, jdziat commented on clean/clean.go
> +	arnmap := map[string]string{
yea, fine for it to default or use a template to update it. But if we ever add accounts it would be easier to update a mapping than it would be to push a code change.

2025-03-17 15:54 UTC, jdziat requested changes
Just a handful of changes we should make

2025-03-17 15:54 UTC, jdziat commented on clean/clean.go
> +				}
I would break the logic for creating an image into a standalone function that returns a valid image instance.

2025-03-17 15:54 UTC, jdziat commented on clean/clean.go
> +	if arn == "arn:aws:iam::722014088219:role/devops-read-only" {
Let's move this into an env variable with a default value set to the expected root account

2025-03-17 15:54 UTC, jdziat commented on clean/clean.go
> +		UID: "W7Xb02Snk",
We should make this configurable and able to scan multiple sources

2025-03-17 15:54 UTC, jdziat commented on clean/clean.go
> +			if deets.ImageTags == nil {
We should keep the last 10(or whatever the config says we should keep) even if they're untagged

2025-03-17 16:16 UTC, will-beep-lamm commented on clean/clean.go
> +			if deets.ImageTags == nil {
If they are untagged, they aren't running anywhere and won't be pulled. What would be the purpose of keeping the untagged images?

2025-03-24 17:49 UTC, jdziat commented on clean/clean.go
> +			if deets.ImageTags == nil {
Rollback purposes in case someone wants to restore to a previous build, also for auditing and secops related actions we may not want to purge that 10 or so most recent images.

2025-04-29 18:56 UTC, closed without merging